### ISSUE TITLE
Apply dropout consecutively  in san.py?

### ISSUE THREAD

**Issue by hsm207** [Artaches/SSAN-self-attention-sentiment-analysis-classification#2]
This is from the end of the definition of ` multi_head_attention` in [san.py](https://github.com/Artaches/SSAN-self-attention-sentiment-analysis-classification/blob/master/san.py):
 
https://github.com/Artaches/SSAN-self-attention-sentiment-analysis-classification/blob/ab3d8d347e074dee73b7bc7f98ed0270eab94745/san.py#L253-L256

And this is the start of the definition of `encoder_layer`, also in `san.py`:

https://github.com/Artaches/SSAN-self-attention-sentiment-analysis-classification/blob/ab3d8d347e074dee73b7bc7f98ed0270eab94745/san.py#L260-L266

It looks like dropout is applied twice in a row with keep_prob=0.70 by default. Is this what was intended?

**Comment by Artaches** [comment]
Thank you for pointing that out! I've removed the extra dropout that's applied in encoder().

**Comment by hsm207** [comment]
Thanks for the clarification.

Will you rerun the experiment to see if it changes the results?

**Comment by Artaches** [comment]
To clarify: I've checked and this bug was not present in my original codebase that was used to get the numbers in the paper. This repository is the (much) cleaned up and simplified version of the codebase I used for my thesis work (https://theses.lib.sfu.ca/file/thesis/4959). Still, I've just rerun this repo with 2layer ssan and got this:

|dataset | acc|
|--------------- | ------------|
|sst_fine | 0.482 ±0.004|
|sst_binary | 0.839 ±0.008|
|opener | 0.832 ±0.010|
|sentube_auto | 0.616 ±0.010|
|sentube_tablets | 0.676 ±0.006|
|semeval | 0.705 ±0.009|
|overall | 0.692 ±0.008|

This is in line with the results from the paper.
