### ISSUE TITLE
strange about mult-head-attentions

### ISSUE THREAD

**Issue by sherlockl01** [Artaches/SSAN-self-attention-sentiment-analysis-classification#3]
I try to use 8 or other numbers more than one in multheads, but to my surprise is that, the parameters of network in 8 heads are less than the one in single heads! I find out that the author want to make sure the output dim of the concatenate heads is the same as the network output. I think this is something they misunderstand that the wo dense layer will insure the dim no matter how the input dim is.Is that my opinion make sense?

**Comment by Artaches** [comment]
Hello, and thank you for bringing this to my attention. This is indeed a bug. As for previous issue, this bug was introduced in my process of cleaning up the code for open-sourcing. This bug was not present in the code used to get results for the paper. 

I've fixed the issue and the number of parameters are now as they should be. For example for model_dim=300, using RPR (max_distance=10),1-layer and 1-head ssan I get 465600 # of parameters. For 1-layer and 4-heads I get 456150. This is as expected since the RPR variables are now smaller dimension, that's what causes the difference in # of parameters.

Here are the calculations for # of parameters for relative position representation (RPR) variables if you're interested:
For 1 head, we have: 12600 = 300 (qkv dim) * 21 (# positions) *  2 (we have two sets of RPR variables, one set for key vectors and one for value vectors)
for 4 heads, we have: 3150 = 75 * 21 * 2. These position variables get re-used for each head.
The difference is 9450 which is exactly the in the total # of parameters above.
